#
# Copyright (c) 2019-2020 P3TERX <https://p3terx.com>
#
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.
#
# https://github.com/P3TERX/Actions-OpenWrt
# Description: Build OpenWrt using GitHub Actions
#

name: Build OpenWrt

on:
  push:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      branch:
        description: 'select a branch'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@main
      with:
        repository: lovehackintosh/openwrt
        ref: 'mpfr'
        path: 'openwrt'

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo -E rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc /etc/mysql
        sudo -E apt update
        sudo -E apt purge -y *aspnet* *dotnet* *android* *firefox* *ghc*
        sudo -E apt full-upgrade -y
        sudo -E apt install -y aria2 build-essential clang flex gawk gettext git libncurses5-dev libssl-dev python3-distutils rsync unzip zlib1g-dev file wget
        sudo -E apt autoremove --purge -y
        sudo -E apt clean
        sudo -E rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc /etc/mysql
        export DOWNLOAD_TOOL_CUSTOM=aria2c

    - name: Checkout packages feed
      uses: actions/checkout@main
      with:
        repository: openwrt/packages
        path: openwrt/feeds/packages

    - name: Checkout luci feed
      uses: actions/checkout@main
      with:
        repository: openwrt/luci
        path: openwrt/feeds/luci

    - name: Checkout routing feed
      uses: actions/checkout@main
      with:
        repository: openwrt/routing
        path: openwrt/feeds/routing

    - name: Checkout telephony feed
      uses: actions/checkout@main
      with:
        repository: openwrt/telephony
        path: openwrt/feeds/telephony

    - name: Update & Install feeds
      working-directory: openwrt
      run: |
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Download package
      working-directory: openwrt
      run: |
        echo CONFIG_ALL_KMODS=y > .config
        echo CONFIG_ALL=y >> .config
        echo CONFIG_DEVEL=y >> .config
        echo CONFIG_AUTOREMOVE=y >> .config
        echo CONFIG_CCACHE=y >> .config
        echo CONFIG_TARGET_x86=y >> .config
        echo CONFIG_TARGET_x86_64=y >> .config
        make defconfig
        ./scripts/diffconfig.sh
        make download -j16

    - name: Compile tools
      working-directory: openwrt
      run: |
        make tools/install -j$(nproc)

    - name: Compile toolchain
      working-directory: openwrt
      run: |
        make toolchain/install -j$(nproc)

    - name: Compile kernel
      working-directory: openwrt
      run: |
        make target/compile -j$(nproc)

    - name: Compile everything
      working-directory: openwrt
      run: |
        make -j$(nproc)

    - name: Check space usage
      run: df -hT

    - name: Upload firmware
      uses: actions/upload-artifact@main
      with:
        name: bin
        path: openwrt/bin
